# --- STATIC HARDENING (Global Security) ---
# Ignore ICMP broadcasts and bogus error responses
net.ipv4.icmp_echo_ignore_broadcasts = 1
net.ipv4.icmp_ignore_bogus_error_responses = 1
# Protection against SYN flood and TCP session hijacking
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_rfc1337 = 1
# Log packets with impossible source addresses
net.ipv4.conf.all.log_martians = 1
net.ipv4.conf.default.log_martians = 1
# Disable source routing and redirects (Server is not a router)
net.ipv4.conf.all.accept_source_route = 0
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.all.accept_redirects = 0
net.ipv4.conf.all.secure_redirects = 0
net.ipv4.ip_forward = 0
net.ipv4.conf.all.send_redirects = 0
# Completely disable IPv6 stack for hardening
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
# Enable full ASLR for memory protection
kernel.randomize_va_space = 2
net.ipv4.tcp_window_scaling = 1

# --- DYNAMIC SECTION (Optimized via SED) ---
fs.file-max = 0
kernel.pid_max = 0
net.ipv4.ip_local_port_range = 1024 65535
net.core.rmem_max = 0
net.core.wmem_max = 0
net.core.netdev_max_backlog = 0
net.core.somaxconn = 0
net.ipv4.tcp_rmem = 4096 8192 0
net.ipv4.tcp_wmem = 4096 8192 0
